# --- ДАННЫЕ КЛУБОВ ---
CLUBS = {
        "Real Madrid": {"emoji": "⚪️", "players": [
        {"name": "Courtois", "rating": 90, "pos": "GK"}, {"name": "Mendy", "rating": 81, "pos": "DEF"}, 
        {"name": "Carreras", "rating": 81, "pos": "DEF"}, {"name": "Huijsen", "rating": 81, "pos": "DEF"}, {"name": "Asencio", "rating": 78, "pos": "DEF"},
        {"name": "Carvajal", "rating": 84, "pos": "DEF"}, {"name": "Militao", "rating": 84, "pos": "DEF"}, 
        {"name": "Rudiger", "rating": 84, "pos": "DEF"}, {"name": "Valverde", "rating": 89, "pos": "MID"}, 
        {"name": "Bellingham", "rating": 89, "pos": "MID"}, {"name": "Brahim", "rating": 81, "pos": "MID"}, 
        {"name": "Rodrygo", "rating": 84, "pos": "FWD"}, {"name": "Mbappe", "rating": 91, "pos": "FWD"}, 
        {"name": "Vinicius", "rating": 89, "pos": "FWD"}, {"name": "Lunin", "rating": 80, "pos": "GK"}, {"name": "Mastantuono", "rating": 77, "pos": "MID"},
        {"name": "Alaba", "rating": 80, "pos": "DEF"}, {"name": "Fran Garcia", "rating": 77, "pos": "DEF"}, {"name": "Trent", "rating": 85, "pos": "DEF/MID"},
        {"name": "Tchouameni", "rating": 84, "pos": "MID"}, {"name": "Camavinga", "rating": 82, "pos": "MID"}, {"name": "Pitarch", "rating": 68, "pos": "MID"},
        {"name": "Guler", "rating": 82, "pos": "MID"}, {"name": "Gonzalo", "rating": 73, "pos": "FWD"},
    ]},
        "Barcelona": {"emoji": "🔵🔴", "players": [
        {"name": "Joan Garcia", "rating": 86, "pos": "GK"}, {"name": "Szczesny", "rating": 83, "pos": "GK"},
        {"name": "Kounde", "rating": 86, "pos": "DEF"}, {"name": "Cancelo", "rating": 84, "pos": "DEF"},
        {"name": "Cubarsi", "rating": 82, "pos": "DEF"}, {"name": "Araujo", "rating": 82, "pos": "DEF"},
        {"name": "Eric Garcia", "rating": 83, "pos": "DEF"}, {"name": "Balde", "rating": 83, "pos": "DEF"}, 
        {"name": "Gerard M.", "rating": 76, "pos": "DEF"}, {"name": "Gavi", "rating": 83, "pos": "MID"}, 
        {"name": "Christensen", "rating": 80, "pos": "DEF"}, {"name": "De Jong", "rating": 87, "pos": "MID"}, 
        {"name": "Casado", "rating": 78, "pos": "MID"}, {"name": "Pedri", "rating": 90, "pos": "MID"}, 
        {"name": "Bernal", "rating": 75, "pos": "MID"}, {"name": "Fermin", "rating": 83, "pos": "MID/FWD"}, 
        {"name": "Dani Olmo", "rating": 84, "pos": "MID/FWD"}, {"name": "Lamine Yamal", "rating": 89, "pos": "FWD"}, 
        {"name": "Bardghji", "rating": 74, "pos": "FWD"}, {"name": "Raphinha", "rating": 89, "pos": "FWD"}, 
        {"name": "Rashford", "rating": 81, "pos": "FWD"}, {"name": "Ferran Torres", "rating": 84, "pos": "FWD"}, 
        {"name": "Lewandowski", "rating": 86, "pos": "FWD"},
    ]},
        "Bayern": {"emoji": "🔴⚪", "players": [
        {"name": "Neuer", "rating": 83, "pos": "GK"}, {"name": "Urbig", "rating": 76, "pos": "GK"},
        {"name": "Stanisic", "rating": 79, "pos": "DEF"}, {"name": "Laimer", "rating": 83, "pos": "DEF"},
        {"name": "Upamecano", "rating": 86, "pos": "DEF"}, {"name": "Kim Min Jae", "rating": 82, "pos": "DEF"},
        {"name": "Tah", "rating": 87, "pos": "DEF"}, {"name": "Ito", "rating": 78, "pos": "DEF"},
        {"name": "Davies", "rating": 84, "pos": "DEF/MID"}, {"name": "Guerreiro", "rating": 80, "pos": "DEF"},
        {"name": "Kimmich", "rating": 89, "pos": "MID/DEF"}, {"name": "Goretzka", "rating": 81, "pos": "MID"},
        {"name": "Pavlovic", "rating": 81, "pos": "MID"}, {"name": "Bischof", "rating": 78, "pos": "MID"},
        {"name": "Gnabry", "rating": 83, "pos": "MID/FWD"}, {"name": "Musiala", "rating": 88, "pos": "MID/FWD"}, {"name": "L. Karl", "rating": 75, "pos": "MID/FWD"},
        {"name": "Olise", "rating": 88, "pos": "FWD"}, {"name": "Luis Diaz", "rating": 87, "pos": "FWD"}, 
        {"name": "W. Mike", "rating": 61, "pos": "FWD"}, {"name": "Kane", "rating": 90, "pos": "FWD"}, 
        {"name": "Jackson", "rating": 79, "pos": "FWD"},
    ]},
        "PSG": {"emoji": "🔵🔴", "players": [
        {"name": "Safonov", "rating": 80, "pos": "GK"}, {"name": "Chevalier", "rating": 82, "pos": "GK"}, 
        {"name": "Hakimi", "rating": 89, "pos": "DEF"}, {"name": "Marquinhos", "rating": 87, "pos": "DEF"}, 
        {"name": "Zabarnyi", "rating": 80, "pos": "DEF"}, {"name": "Pacho", "rating": 87, "pos": "DEF"}, 
        {"name": "Lucas Beraldo", "rating": 78, "pos": "DEF"}, {"name": "Nuno Mendes", "rating": 88, "pos": "DEF"}, 
        {"name": "Lucas Hernandez", "rating": 81, "pos": "DEF"}, {"name": "Vitinha", "rating": 90, "pos": "MID"}, 
        {"name": "Zaire-Emery", "rating": 81, "pos": "MID"}, {"name": "Joao Neves", "rating": 87, "pos": "MID"},
        {"name": "Fabian Ruiz", "rating": 85, "pos": "MID"}, {"name": "Doue", "rating": 85, "pos": "FWD"}, 
        {"name": "Lee Kang In", "rating": 80, "pos": "FWD/MID"}, {"name": "Dembélé", "rating": 90, "pos": "FWD"}, 
        {"name": "Gonçalo Ramos", "rating": 80, "pos": "FWD"}, {"name": "Kvaratskhelia", "rating": 87, "pos": "FWD"}, 
        {"name": "Barcola", "rating": 84, "pos": "FWD"}, {"name": "Mayulu", "rating": 76, "pos": "MID/FWD"}, 
        {"name": "Mbaye", "rating": 74, "pos": "FWD/MID"}
    ]},
        "Inter": {"emoji": "🔵⚫", "players": [
        {"name": "Sommer", "rating": 86, "pos": "GK"}, {"name": "Josep Martinez", "rating": 75, "pos": "GK"},
        {"name": "Luis Henrique", "rating": 78, "pos": "DEF"}, {"name": "Darmian", "rating": 78, "pos": "DEF"},
        {"name": "Bisseck", "rating": 76, "pos": "DEF"}, {"name": "Akanji", "rating": 83, "pos": "DEF"}, 
        {"name": "Acerbi", "rating": 83, "pos": "DEF"}, {"name": "Bastoni", "rating": 87, "pos": "DEF"}, 
        {"name": "De Vrij", "rating": 83, "pos": "DEF"}, {"name": "Dimarco", "rating": 86, "pos": "DEF/MID"}, {"name": "Dumfries", "rating": 84, "pos": "DEF/MID"},
        {"name": "Carlos Augusto", "rating": 81, "pos": "DEF"}, {"name": "Calhanoglu", "rating": 86, "pos": "MID"},
        {"name": "Frattesi", "rating": 81, "pos": "MID"}, {"name": "Barella", "rating": 88, "pos": "MID"}, 
        {"name": "Mkhitaryan", "rating": 83, "pos": "MID"}, {"name": "Zielinski", "rating": 81, "pos": "MID"}, 
        {"name": "Diouf", "rating": 75, "pos": "MID"}, {"name": "Thuram", "rating": 85, "pos": "FWD"}, {"name": "Esposito", "rating": 76, "pos": "FWD"},
        {"name": "Bonny", "rating": 78, "pos": "FWD"}, {"name": "Lautaro Martinez", "rating": 88, "pos": "FWD"}
    ]},
        "Milan": {"emoji": "🔴⚫", "players": [
        {"name": "Maignan", "rating": 87, "pos": "GK"}, {"name": "Terracciano", "rating": 78, "pos": "GK"},
        {"name": "Saelemaekers", "rating": 80, "pos": "DEF"}, {"name": "Athekame", "rating": 65, "pos": "DEF"},
        {"name": "Tomori", "rating": 81, "pos": "DEF"}, {"name": "Gabbia", "rating": 80, "pos": "DEF"}, 
        {"name": "Pavlovic", "rating": 77, "pos": "DEF"}, {"name": "De Winter", "rating": 74, "pos": "DEF"},
        {"name": "Bartesaghi", "rating": 71, "pos": "DEF"}, {"name": "Estupinan", "rating": 79, "pos": "DEF"},
        {"name": "Modric", "rating": 84, "pos": "MID"}, {"name": "Fofana", "rating": 81, "pos": "MID"},
        {"name": "Ricci", "rating": 79, "pos": "MID"}, {"name": "Loftus-Cheek", "rating": 80, "pos": "MID"},
        {"name": "Rabiot", "rating": 84, "pos": "MID"}, {"name": "Jashari", "rating": 77, "pos": "MID"},
        {"name": "Pulisic", "rating": 85, "pos": "FWD"}, {"name": "Fullkrug", "rating": 78, "pos": "FWD"},
        {"name": "Rafael Leao", "rating": 84, "pos": "FWD"}, {"name": "Gimenez", "rating": 79, "pos": "FWD"}, 
        {"name": "Nkunku", "rating": 81, "pos": "FWD"}
    ]},

        "Ajax": {"emoji": "⚪🔴", "players": [
        {"name": "Paes", "rating": 71, "pos": "GK"}, {"name": "Jaroš", "rating": 72, "pos": "GK"},
        {"name": "Lucas Rosa", "rating": 71, "pos": "DEF"}, {"name": "Gaaei", "rating": 71, "pos": "DEF"},
        {"name": "Šutalo", "rating": 77, "pos": "DEF"}, {"name": "Itakura", "rating": 76, "pos": "DEF"},
        {"name": "Baas", "rating": 77, "pos": "DEF"}, {"name": "Tomiyasu", "rating": 77, "pos": "DEF"},
        {"name": "Wijndal", "rating": 71, "pos": "DEF"}, {"name": "Jetten", "rating": 62, "pos": "DEF"},
        {"name": "Zinchenko", "rating": 77, "pos": "DEF/MID"}, {"name": "Regeer", "rating": 73, "pos": "MID"},
        {"name": "Mokio", "rating": 69, "pos": "MID"}, {"name": "Klaassen", "rating": 76, "pos": "MID"},
        {"name": "Fitz-Jim", "rating": 72, "pos": "MID"}, {"name": "Steur", "rating": 67, "pos": "MID"}, {"name": "Edvardsen", "rating": 72, "pos": "MID"},
        {"name": "Berghuis", "rating": 77, "pos": "FWD"}, {"name": "Bounida", "rating": 66, "pos": "FWD"},
        {"name": "Godts", "rating": 77, "pos": "FWD"}, {"name": "Gloukh", "rating": 77, "pos": "FWD"},
        {"name": "Weghorst", "rating": 77, "pos": "FWD"}, {"name": "Dolberg", "rating": 77, "pos": "FWD"} , {"name": "Carrizo", "rating": 74, "pos": "FWD"}
    ]},
    
      "Bayer Leverkusen": {"emoji": "⚫🔴", "players": [
        {"name": "Blaswich", "rating": 73, "pos": "GK"}, {"name": "Omlin", "rating": 74, "pos": "GK"}, 
        {"name": "Flekken", "rating": 78, "pos": "GK"}, {"name": "Quansah", "rating": 76, "pos": "DEF"}, 
        {"name": "Oermann", "rating": 72, "pos": "DEF"}, {"name": "Andrich", "rating": 79, "pos": "DEF"}, 
        {"name": "Lade", "rating": 78, "pos": "DEF"}, {"name": "Tapsoba", "rating": 82, "pos": "DEF"}, 
        {"name": "Tella", "rating": 78, "pos": "MID"}, {"name": "Arthur", "rating": 73, "pos": "MID"},
        {"name": "Poku", "rating": 76, "pos": "MID"}, {"name": "Lucas Vazquez", "rating": 77, "pos": "MID/DEF"},
        {"name": "Aleix Garcia", "rating": 84, "pos": "MID"}, {"name": "Mensah", "rating": 62, "pos": "MID"},
        {"name": "Palacios", "rating": 83, "pos": "MID"}, {"name": "Enzo Fernandez", "rating": 76, "pos": "MID"},
        {"name": "Grimaldo", "rating": 85, "pos": "MID/DEF"}, {"name": "Maza", "rating": 78, "pos": "FWD"},
        {"name": "Hofmann", "rating": 77, "pos": "FWD"}, {"name": "Tillman", "rating": 80, "pos": "FWD"},
        {"name": "Terrier", "rating": 79, "pos": "FWD/MID"}, {"name": "Schick", "rating": 85, "pos": "FWD"}, 
        {"name": "Kofane", "rating": 75, "pos": "FWD"}
    ]},
      "Juventus": {"emoji": "⚪⚫", "players": [
        {"name": "Di Gregorio", "rating": 81, "pos": "GK"}, {"name": "Pinsoglio", "rating": 69, "pos": "GK"}, 
        {"name": "Perin", "rating": 78, "pos": "GK"}, {"name": "Kalulu", "rating": 80, "pos": "DEF"}, 
        {"name": "Kabal", "rating": 74, "pos": "DEF"}, {"name": "Bremer", "rating": 86, "pos": "DEF"}, 
        {"name": "Gatti", "rating": 80, "pos": "DEF"}, {"name": "L. Kelly", "rating": 77, "pos": "DEF"},
        {"name": "McKennie", "rating": 78, "pos": "MID"}, {"name": "Holm", "rating": 74, "pos": "MID"},
        {"name": "Locatelli", "rating": 84, "pos": "MID"}, {"name": "Miretti", "rating": 75, "pos": "MID"}, 
        {"name": "K. Thuram", "rating": 81, "pos": "MID"}, {"name": "Zhegrova", "rating": 79, "pos": "MID/FWD"},
        {"name": "Cambiaso", "rating": 80, "pos": "MID/DEF"}, {"name": "Kostic", "rating": 80, "pos": "MID/FWD"},
        {"name": "Conceicao", "rating": 79, "pos": "FWD/MID"}, {"name": "Adzic", "rating": 67, "pos": "FWD"}, 
        {"name": "Vlahović", "rating": 81, "pos": "FWD"}, {"name": "Yildiz", "rating": 81, "pos": "FWD"}, 
        {"name": "Koopmeiners", "rating": 80, "pos": "MID"}, {"name": "Milik", "rating": 78, "pos": "FWD"},
        {"name": "Jonathan David", "rating": 81, "pos": "FWD"}, {"name": "Openda", "rating": 82, "pos": "FWD"}, 
        {"name": "Boga", "rating": 75, "pos": "FWD"}
    ]},
        "Borussia Dortmund": {"emoji": "🟡⚫", "players": [
        {"name": "Kobel", "rating": 86, "pos": "GK"}, {"name": "Meyer", "rating": 75, "pos": "GK"}, 
        {"name": "Drewes", "rating": 75, "pos": "GK"}, {"name": "Bensebaini", "rating": 79, "pos": "DEF"}, 
        {"name": "Sule", "rating": 78, "pos": "DEF"}, {"name": "E. Can", "rating": 82, "pos": "DEF/MID"},
        {"name": "Anton", "rating": 83, "pos": "DEF"}, {"name": "Lucciana", "rating": 61, "pos": "DEF"},
        {"name": "Schlotterbeck", "rating": 86, "pos": "DEF"}, {"name": "Kabar", "rating": 64, "pos": "DEF"},
        {"name": "Ryerson", "rating": 80, "pos": "MID/DEF"}, {"name": "Adeyemi", "rating": 82, "pos": "FWD/MID"},
        {"name": "Sabitzer", "rating": 81, "pos": "MID"}, {"name": "Jobe Bellingham", "rating": 76, "pos": "MID"},
        {"name": "Nmecha", "rating": 84, "pos": "MID"}, {"name": "Yan Couto", "rating": 79, "pos": "MID/DEF"},
        {"name": "Svensson", "rating": 79, "pos": "MID"}, {"name": "Özcan", "rating": 74, "pos": "MID"},
        {"name": "Beier", "rating": 79, "pos": "FWD"}, {"name": "Chukwuemeka", "rating": 78, "pos": "FWD/MID"},
        {"name": "Brandt", "rating": 83, "pos": "FWD/MID"}, {"name": "Guirassy", "rating": 85, "pos": "FWD"}, 
        {"name": "Fabio Silva", "rating": 79, "pos": "FWD"}
    ]},
        "Atletico Madrid": {"emoji": "🔴⚪", "players": [
        {"name": "Oblak", "rating": 88, "pos": "GK"}, {"name": "Musso", "rating": 79, "pos": "GK"},
        {"name": "Marcos Llorente", "rating": 84, "pos": "DEF"}, {"name": "Molina", "rating": 77, "pos": "DEF"},
        {"name": "Pubill", "rating": 78, "pos": "DEF"}, {"name": "Gimenez", "rating": 82, "pos": "DEF"}, 
        {"name": "Le Normand", "rating": 81, "pos": "DEF"}, {"name": "Hancko", "rating": 83, "pos": "DEF"}, 
        {"name": "Lenglet", "rating": 78, "pos": "DEF"}, {"name": "Ruggeri", "rating": 77, "pos": "DEF"}, 
        {"name": "Julio Diaz", "rating": 62, "pos": "DEF"}, {"name": "Simeone", "rating": 81, "pos": "FWD/MID"}, 
        {"name": "Rayane", "rating": 61, "pos": "MID"}, {"name": "Pablo Barrios", "rating": 83, "pos": "MID"}, 
        {"name": "Johnny Cardoso", "rating": 80, "pos": "MID"}, {"name": "Vargas", "rating": 71, "pos": "MID"},
        {"name": "Koke", "rating": 81, "pos": "MID"}, {"name": "Jano Monserrate", "rating": 58, "pos": "MID"}, 
        {"name": "Mendoza", "rating": 71, "pos": "MID"}, {"name": "Alex Baena", "rating": 83, "pos": "FWD/MID"}, 
        {"name": "Nico Gonzalez", "rating": 79, "pos": "MID"}, {"name": "Almada", "rating": 79, "pos": "MID"},
        {"name": "Sorloth", "rating": 83, "pos": "FWD"}, {"name": "Lookman", "rating": 83, "pos": "FWD"},
        {"name": "Alvarez", "rating": 86, "pos": "FWD"}, {"name": "Griezmann", "rating": 84, "pos": "FWD"}
    ]},

    # --АПЛ--

        "Chelsea": {"emoji": "🔵", "players": [
        {"name": "Sanchez", "rating": 81, "pos": "GK"}, {"name": "Jorgensen", "rating": 77, "pos": "GK"}, 
        {"name": "Słonina", "rating": 68, "pos": "GK"}, {"name": "Reece James", "rating": 84, "pos": "DEF/MID"}, 
        {"name": "Gusto", "rating": 79, "pos": "DEF"}, {"name": "Acheampong", "rating": 73, "pos": "DEF"},
        {"name": "Chalobah", "rating": 80, "pos": "DEF"}, {"name": "Adarabioyo", "rating": 78, "pos": "DEF"}, 
        {"name": "Sarr", "rating": 77, "pos": "DEF"}, {"name": "Cucurella", "rating": 85, "pos": "DEF"}, 
        {"name": "Hato", "rating": 78, "pos": "DEF"}, {"name": "Colwill", "rating": 80, "pos": "DEF"},
        {"name": "Caicedo", "rating": 88, "pos": "MID"}, {"name": "Enzo Fernandez", "rating": 85, "pos": "MID"}, 
        {"name": "Andrey Santos", "rating": 80, "pos": "MID"}, {"name": "Palmer", "rating": 86, "pos": "MID/FWD"}, 
        {"name": "Estevao", "rating": 79, "pos": "FWD"}, {"name": "Lavia", "rating": 78, "pos": "MID"}, 
        {"name": "Dário Essugo", "rating": 75, "pos": "MID"}, {"name": "Neto", "rating": 82, "pos": "FWD"}, 
        {"name": "Garnacho", "rating": 78, "pos": "FWD"}, {"name": "Delap", "rating": 78, "pos": "FWD"},
        {"name": "Joao Pedro", "rating": 81, "pos": "FWD"}, {"name": "Guiu", "rating": 71, "pos": "FWD"}
    ]},
        "Man City": {"emoji": "🔵", "players": [
        {"name": "Donnarumma", "rating": 88, "pos": "GK"}, {"name": "Trafford", "rating": 76, "pos": "GK"}, 
        {"name": "Nunes", "rating": 81, "pos": "DEF"},  {"name": "Khusanov", "rating": 79, "pos": "DEF"},
        {"name": "Dias", "rating": 87, "pos": "DEF"}, {"name": "Aït Nouri", "rating": 81, "pos": "DEF"}, 
        {"name": "Gvardiol", "rating": 85, "pos": "DEF"}, {"name": "Rodri", "rating": 89, "pos": "MID"}, 
        {"name": "González", "rating": 81, "pos": "MID"}, {"name": "Bernardo", "rating": 83, "pos": "MID"}, 
        {"name": "Foden", "rating": 85, "pos": "FWD/MID"}, {"name": "Haaland", "rating": 91, "pos": "FWD"}, 
        {"name": "Doku", "rating": 83, "pos": "FWD"}, 
        {"name": "Ake", "rating": 82, "pos": "DEF"}, {"name": "Lewis", "rating": 77, "pos": "DEF"}, 
        {"name": "Guehi", "rating": 84, "pos": "DEF"}, 
        {"name": "Stones", "rating": 82, "pos": "DEF"}, {"name": "O'Reilly", "rating": 80, "pos": "DEF/MID"}, 
        {"name": "Kovacic", "rating": 82, "pos": "MID"}, {"name": "Reijnders", "rating": 85, "pos": "MID"}, 
        {"name": "Savinho", "rating": 81, "pos": "FWD"}, {"name": "Semenyo", "rating": 83, "pos": "FWD"}, 
        {"name": "Marmoush", "rating": 83, "pos": "FWD"}, {"name": "Cherki", "rating": 83, "pos": "FWD"}
    ]},
        "Arsenal": {"emoji": "🔴", "players": [
        {"name": "Raya", "rating": 87, "pos": "GK"}, {"name": "Kepa", "rating": 79, "pos": "GK"},
        {"name": "Timber", "rating": 84, "pos": "DEF"}, {"name": "White", "rating": 82, "pos": "DEF"},
        {"name": "Saliba", "rating": 88, "pos": "DEF"}, {"name": "Mosquera", "rating": 77, "pos": "DEF"},
        {"name": "Gabriel", "rating": 89, "pos": "DEF"}, {"name": "Jesus", "rating": 80, "pos": "FWD"},
        {"name": "Hincapie", "rating": 83, "pos": "DEF"}, {"name": "Calafiori", "rating": 82, "pos": "DEF"},
        {"name": "Zubimendi", "rating": 85, "pos": "MID"}, {"name": "Norgaard", "rating": 80, "pos": "MID"},
        {"name": "Odegaard", "rating": 86, "pos": "MID"}, {"name": "Eze", "rating": 84, "pos": "MID/FWD"}, 
        {"name": "Rice", "rating": 88, "pos": "MID"}, {"name": "Merino", "rating": 83, "pos": "MID/FWD"},
        {"name": "Saka", "rating": 87, "pos": "FWD"}, {"name": "Madueke", "rating": 80, "pos": "FWD"}, 
        {"name": "Lewis-Skelly", "rating": 78, "pos": "DEF/MID"}, {"name": "Gyokeres", "rating": 86, "pos": "FWD"}, 
        {"name": "Havertz", "rating": 82, "pos": "FWD/MID"}, {"name": "Trossard", "rating": 83, "pos": "FWD"}, 
        {"name": "Martinelli", "rating": 81, "pos": "FWD"}
    ]},
        "Liverpool": {"emoji": "🔴", "players": [
        {"name": "Alisson", "rating": 88, "pos": "GK"}, {"name": "Mamardashvili", "rating": 83, "pos": "GK"},
        {"name": "Szoboszlai", "rating": 86, "pos": "MID/DEF"}, {"name": "Ramsay", "rating": 65, "pos": "DEF"},
        {"name": "Konate", "rating": 85, "pos": "DEF"}, {"name": "Gomez", "rating": 79, "pos": "DEF"},
        {"name": "van Dijk", "rating": 88, "pos": "DEF"}, {"name": "Bradley", "rating": 79, "pos": "DEF"},
        {"name": "Kerkez", "rating": 81, "pos": "DEF"}, {"name": "Robertson", "rating": 81, "pos": "DEF"},
        {"name": "Gravenberch", "rating": 86, "pos": "MID"}, {"name": "Jones", "rating": 80, "pos": "MID"},
        {"name": "Mac Allister", "rating": 86, "pos": "MID"}, {"name": "Frimpong", "rating": 83, "pos": "DEF/MID/FWD"},
        {"name": "Wirtz", "rating": 87, "pos": "MID"}, {"name": "Endo", "rating": 79, "pos": "MID"}, 
        {"name": "Leoni", "rating": 69, "pos": "DEF"}, {"name": "Salah", "rating": 89, "pos": "FWD"}, 
        {"name": "Chiesa", "rating": 80, "pos": "FWD"}, {"name": "Gakpo", "rating": 83, "pos": "FWD"}, 
        {"name": "Ngumoha", "rating": 70, "pos": "FWD"}, {"name": "Ekitike", "rating": 85, "pos": "FWD"}, 
        {"name": "Isak", "rating": 87, "pos": "FWD"}
    ]},

        "Newcastle": {"emoji": "🦓", "players": [
        {"name": "Pope", "rating": 80, "pos": "GK"}, {"name": "Ramsdale", "rating": 77, "pos": "GK"},
        {"name": "Trippier", "rating": 79, "pos": "DEF"}, {"name": "Livramento", "rating": 80, "pos": "DEF"},
        {"name": "Thiaw", "rating": 81, "pos": "DEF"}, {"name": "Schär", "rating": 83, "pos": "DEF"}, {"name": "Krafth", "rating": 72, "pos": "DEF"},
        {"name": "Burn", "rating": 80, "pos": "DEF"}, {"name": "Botman", "rating": 82, "pos": "DEF"},
        {"name": "Hall", "rating": 81, "pos": "DEF"}, {"name": "Murphy", "rating": 65, "pos": "DEF"},
        {"name": "Tonali", "rating": 85, "pos": "MID"}, {"name": "Ramsey", "rating": 77, "pos": "MID"},
        {"name": "Willock", "rating": 76, "pos": "MID"}, {"name": "Miley", "rating": 76, "pos": "MID"},
        {"name": "Bruno Guimarães", "rating": 86, "pos": "MID"}, {"name": "Joelinton", "rating": 81, "pos": "MID"},
        {"name": "Barnes", "rating": 80, "pos": "MID/FWD"}, {"name": "Murphy", "rating": 80, "pos": "MID"},
        {"name": "Gordon", "rating": 83, "pos": "FWD/MID"}, {"name": "Woltemade", "rating": 80, "pos": "FWD"}, {"name": "Elanga", "rating": 79, "pos": "FWD/MID"},
        {"name": "Osula", "rating": 73, "pos": "FWD"}, {"name": "Wissa", "rating": 82, "pos": "FWD"}
    ]},

        "Manchester United": {"emoji": "🔴", "players": [
        {"name": "Lammens", "rating": 80, "pos": "GK"}, {"name": "Bayindir", "rating": 75, "pos": "GK"}, {"name": "Heaton", "rating": 67, "pos": "GK"},
        {"name": "Dalot", "rating": 78, "pos": "DEF"}, {"name": "Mazraoui", "rating": 80, "pos": "DEF"}, {"name": "Heaven", "rating": 73, "pos": "DEF"}, {"name": "León", "rating": 64, "pos": "DEF"},
        {"name": "Yoro", "rating": 78, "pos": "DEF"}, {"name": "De Ligt", "rating": 82, "pos": "DEF"}, {"name": "Dorgu", "rating": 77, "pos": "MID/DEF"},
        {"name": "Maguire", "rating": 81, "pos": "DEF"}, {"name": "Martinez", "rating": 81, "pos": "DEF"},
        {"name": "Shaw", "rating": 79, "pos": "DEF"}, {"name": "Malacia", "rating": 75, "pos": "DEF"},
        {"name": "Casemiro", "rating": 82, "pos": "MID"}, {"name": "Ugarte", "rating": 78, "pos": "MID"}, {"name": "Mount", "rating": 78, "pos": "MID"},
        {"name": "Mainoo", "rating": 78, "pos": "MID"}, {"name": "Bruno Fernandes", "rating": 88, "pos": "MID"},
        {"name": "Amad", "rating": 80, "pos": "FWD/MID/DEF"}, {"name": "Matheus Cunha", "rating": 83, "pos": "FWD/MID"},
        {"name": "Mbeumo", "rating": 85, "pos": "FWD"}, {"name": "Sesko", "rating": 80, "pos": "FWD"}, {"name": "Zirkzee", "rating": 77, "pos": "FWD"}
    ]},

        "Monaco": {"emoji": "👑", "players": [
        {"name": "Hrádecký", "rating": 80, "pos": "GK"}, {"name": "Köhn", "rating": 77, "pos": "GK"},
        {"name": "Vanderson", "rating": 77, "pos": "DEF"}, {"name": "Diatta", "rating": 74, "pos": "DEF"},
        {"name": "Kehrer", "rating": 78, "pos": "DEF"}, {"name": "Zakaria", "rating": 81, "pos": "DEF"},
        {"name": "Dier", "rating": 78, "pos": "DEF"}, {"name": "Faes", "rating": 74, "pos": "DEF"},
        {"name": "Caio Henrique", "rating": 77, "pos": "DEF"}, {"name": "Ansu Fati", "rating": 75, "pos": "FWD"},
        {"name": "Ouattara", "rating": 72, "pos": "MID"}, {"name": "Adingra", "rating": 76, "pos": "MID"},
        {"name": "Idumbo", "rating": 68, "pos": "MID"}, {"name": "Minamino", "rating": 78, "pos": "FWD"},
        {"name": "Camara", "rating": 79, "pos": "MID"}, {"name": "Pogba", "rating": 78, "pos": "MID"},
        {"name": "Bamba", "rating": 69, "pos": "MID"}, {"name": "Coulibaly", "rating": 71, "pos": "MID"},
        {"name": "Akliouche", "rating": 80, "pos": "MID"}, {"name": "Golovin", "rating": 79, "pos": "MID"}, {"name": "Teze", "rating": 77, "pos": "MID"},
        {"name": "Balogun", "rating": 79, "pos": "FWD"}, {"name": "Biereth", "rating": 77, "pos": "FWD"}
    ]},

        "Athletic Bilbao": {"emoji": "⛪", "players": [
        {"name": "Unai Simón", "rating": 84, "pos": "GK"}, {"name": "Álex Padilla", "rating": 69, "pos": "GK"},
        {"name": "Areso", "rating": 77, "pos": "DEF"}, {"name": "Gorosabel", "rating": 76, "pos": "DEF"}, {"name": "Lekue", "rating": 73, "pos": "DEF"},
        {"name": "Vivian", "rating": 83, "pos": "DEF"}, {"name": "Aitor Paredes", "rating": 78, "pos": "DEF"},
        {"name": "Egiluz", "rating": 70, "pos": "DEF"}, {"name": "Laporte", "rating": 82, "pos": "DEF"},
        {"name": "Iker Monreal", "rating": 59, "pos": "DEF"}, {"name": "Yuri Berchiche", "rating": 79, "pos": "DEF"},
        {"name": "Boiro", "rating": 73, "pos": "DEF"}, {"name": "Ruiz de Galarreta", "rating": 80, "pos": "MID"}, {"name": "Beñat Prados", "rating": 77, "pos": "MID"},
        {"name": "Rego", "rating": 71, "pos": "MID"}, {"name": "Jauregizar", "rating": 80, "pos": "MID"},
        {"name": "Vesga", "rating": 73, "pos": "MID"}, {"name": "Sancet", "rating": 82, "pos": "MID"},
        {"name": "Unai Gómez", "rating": 73, "pos": "MID"}, {"name": "Iñaki Williams", "rating": 82, "pos": "FWD/MID"},
        {"name": "Berenguer", "rating": 81, "pos": "FWD"}, {"name": "Nico Williams", "rating": 85, "pos": "FWD/MID"},
        {"name": "Nico Serrano", "rating": 70, "pos": "FWD"}, {"name": "Guruzeta", "rating": 78, "pos": "FWD"},
        {"name": "Izeta", "rating": 71, "pos": "FWD"}, {"name": "Maroan", "rating": 73, "pos": "FWD"},
    ]},

        "Napoli": {"emoji": "🫏", "players": [
        {"name": "Milinković-Savić", "rating": 79, "pos": "GK"}, {"name": "Meret", "rating": 82, "pos": "GK"},
        {"name": "Buongiorno", "rating": 82, "pos": "DEF"}, {"name": "Rrahmani", "rating": 83, "pos": "DEF"},
        {"name": "Juan Jesus", "rating": 75, "pos": "DEF"}, {"name": "Beukema", "rating": 77, "pos": "DEF"}, {"name": "Di Lorenzo", "rating": 83, "pos": "DEF"},
        {"name": "Politano", "rating": 81, "pos": "MID"}, {"name": "Vergara", "rating": 67, "pos": "MID"},
        {"name": "Lobotka", "rating": 83, "pos": "MID"}, {"name": "Olivera", "rating": 77, "pos": "MID/FWD"},
        {"name": "Gilmour", "rating": 74, "pos": "MID"}, {"name": "Zambo Anguissa", "rating": 83, "pos": "MID"},
        {"name": "Spinazzola", "rating": 80, "pos": "MID"}, {"name": "David Neres", "rating": 81, "pos": "MID/FWD"},
        {"name": "Elmas", "rating": 77, "pos": "MID"}, {"name": "Miguel Gutiérrez", "rating": 81, "pos": "MID"},
        {"name": "McTominay", "rating": 86, "pos": "MID"}, {"name": "De Bruyne", "rating": 87, "pos": "MID"},
        {"name": "Alisson", "rating": 68, "pos": "FWD"}, {"name": "Højlund", "rating": 77, "pos": "FWD"},
        {"name": "Giovane", "rating": 68, "pos": "FWD"}, {"name": "Lukaku", "rating": 83, "pos": "FWD"},
    ]},

        "Brighton": {"emoji": "🔵⚪", "players": [
        {"name": "Verbruggen", "rating": 80, "pos": "GK"}, {"name": "Steele", "rating": 73, "pos": "GK"},
        {"name": "Wieffer", "rating": 78, "pos": "DEF"}, {"name": "Veltman", "rating": 78, "pos": "DEF"},
        {"name": "van Hecke", "rating": 79, "pos": "DEF"}, {"name": "Webster", "rating": 75, "pos": "DEF"}, {"name": "Igor Julio", "rating": 75, "pos": "DEF"},
        {"name": "Dunk", "rating": 77, "pos": "DEF"}, {"name": "Boscagli", "rating": 78, "pos": "DEF"},
        {"name": "Kadıoğlu", "rating": 79, "pos": "DEF"}, {"name": "De Cuyper", "rating": 79, "pos": "DEF"},
        {"name": "Baleba", "rating": 80, "pos": "MID"}, {"name": "Gómez", "rating": 76, "pos": "MID"},
        {"name": "Hinshelwood", "rating": 76, "pos": "MID"}, {"name": "Milner", "rating": 73, "pos": "MID"},
        {"name": "Groß", "rating": 78, "pos": "MID"}, {"name": "Ayari", "rating": 79, "pos": "MID"},
        {"name": "O'Riley", "rating": 77, "pos": "MID"}, {"name": "Minteh", "rating": 80, "pos": "FWD"},
        {"name": "Mitoma", "rating": 82, "pos": "FWD/MID"}, {"name": "Welbeck", "rating": 79, "pos": "FWD"}, {"name": "Tzimas", "rating": 72, "pos": "FWD"},
        {"name": "Rutter", "rating": 77, "pos": "FWD"}, {"name": "Kostoulas", "rating": 73, "pos": "FWD"},
    ]},

        "Tottenham": {"emoji": "⚪", "players": [
        {"name": "Vicario", "rating": 82, "pos": "GK"}, {"name": "Kinsky", "rating": 75, "pos": "GK"},
        {"name": "Danso", "rating": 79, "pos": "DEF"},
        {"name": "Romero", "rating": 83, "pos": "DEF"}, {"name": "Dragusin", "rating": 75, "pos": "DEF"}, 
        {"name": "Udogie", "rating": 79, "pos": "DEF"}, {"name": "van de Ven", "rating": 83, "pos": "DEF"}, 
        {"name": "Ben Davies", "rating": 75, "pos": "DEF"}, {"name": "Djed Spence", "rating": 79, "pos": "DEF"}, 
        {"name": "Souza", "rating": 70, "pos": "DEF"}, {"name": "Gallagher", "rating": 80, "pos": "MID"}, 
        {"name": "Palhinha", "rating": 83, "pos": "MID"}, {"name": "Bentancur", "rating": 80, "pos": "MID"},
        {"name": "Gray", "rating": 76, "pos": "MID"}, {"name": "Bissouma", "rating": 78, "pos": "MID"}, 
        {"name": "Sarr", "rating": 80, "pos": "MID"}, {"name": "Bergvall", "rating": 78, "pos": "FWD"},
        {"name": "Xavi Simons", "rating": 82, "pos": "MID"}, {"name": "Maddison", "rating": 83, "pos": "MID"}, 
        {"name": "Kolo Muani", "rating": 79, "pos": "FWD"}, {"name": "Kudus", "rating": 81, "pos": "FWD"},
        {"name": "Tel", "rating": 77, "pos": "FWD"}, {"name": "Odobert", "rating": 77, "pos": "FWD"}, 
        {"name": "Kulusevski", "rating": 83, "pos": "FWD"}, {"name": "Solanke", "rating": 80, "pos": "FWD"}, 
        {"name": "Richarlison", "rating": 79, "pos": "FWD"}
    ]},

        "Aston Villa": {"emoji": "🦁", "players": [
        {"name": "Martínez", "rating": 85, "pos": "GK"}, {"name": "Bizot", "rating": 78, "pos": "GK"},
        {"name": "Cash", "rating": 81, "pos": "DEF"}, {"name": "Andrés G.", "rating": 73, "pos": "DEF"},
        {"name": "Konsa", "rating": 84, "pos": "DEF"}, {"name": "Lindelöf", "rating": 76, "pos": "DEF"},
        {"name": "Pau Torres", "rating": 80, "pos": "DEF"}, {"name": "Mings", "rating": 78, "pos": "DEF"},
        {"name": "Digne", "rating": 80, "pos": "DEF"}, {"name": "Maatsen", "rating": 79, "pos": "DEF"},
        {"name": "Onana", "rating": 81, "pos": "MID"}, {"name": "Bogarde", "rating": 74, "pos": "MID"},
        {"name": "Douglas Luiz", "rating": 79, "pos": "MID"}, {"name": "Hemmingsen", "rating": 65, "pos": "MID"},
        {"name": "Rogers", "rating": 84, "pos": "MID"}, {"name": "Barkley", "rating": 77, "pos": "MID/FWD"},
        {"name": "Elliott", "rating": 78, "pos": "MID"}, {"name": "Tielemans", "rating": 85, "pos": "MID"},
        {"name": "Kamara", "rating": 84, "pos": "MID"}, {"name": "McGinn", "rating": 81, "pos": "MID"},
        {"name": "Bailey", "rating": 78, "pos": "MID"}, {"name": "Buendía", "rating": 78, "pos": "MID"},
        {"name": "Sancho", "rating": 79, "pos": "FWD"}, {"name": "Watkins", "rating": 82, "pos": "FWD"},
        {"name": "Abraham", "rating": 77, "pos": "FWD"}
    ]},

        "Club Brugge": {"emoji": "🔵⚫", "players": [
        {"name": "Jackers", "rating": 70, "pos": "GK"}, {"name": "van de Heuvel", "rating": 62, "pos": "GK"},
        {"name": "Sabbe", "rating": 72, "pos": "DEF"}, {"name": "Siquet", "rating": 70, "pos": "DEF"},
        {"name": "Ordoñez", "rating": 76, "pos": "DEF"}, {"name": "Osuji", "rating": 65, "pos": "DEF"},
        {"name": "Mechele", "rating": 78, "pos": "DEF"}, {"name": "Seys", "rating": 74, "pos": "DEF"},
        {"name": "Meijer", "rating": 73, "pos": "DEF"}, {"name": "Onyedika", "rating": 78, "pos": "MID"},
        {"name": "Reis", "rating": 72, "pos": "MID"}, {"name": "Vanaken", "rating": 81, "pos": "MID"},
        {"name": "Stanković", "rating": 72, "pos": "MID"}, {"name": "Lemaréchal", "rating": 74, "pos": "MID"}, {"name": "Carlos Forbs", "rating": 72, "pos": "FWD"},
        {"name": "Vetlesen", "rating": 71, "pos": "FWD/MID"}, {"name": "Diakhon", "rating": 70, "pos": "FWD/MID"},
        {"name": "Tzolis", "rating": 81, "pos": "FWD/MID"}, {"name": "Tresoldi", "rating": 74, "pos": "FWD"},
        {"name": "Sandra", "rating": 66, "pos": "FWD/MID"}, {"name": "Vermant", "rating": 72, "pos": "FWD"},
        {"name": "Nilsson", "rating": 73, "pos": "FWD"}
    ]},

        "Real Sociedad": {"emoji": "⚪🔵", "players": [
        {"name": "Álex Remiro", "rating": 82, "pos": "GK"}, {"name": "Unai Marrero", "rating": 70, "pos": "GK"},
        {"name": "J. Aramburu", "rating": 77, "pos": "DEF"}, {"name": "Odriozola", "rating": 73, "pos": "DEF"}, {"name": "Aritz Elustondo", "rating": 74, "pos": "DEF"},
        {"name": "Jon Martín", "rating": 76, "pos": "DEF"}, {"name": "Zubeldia", "rating": 77, "pos": "DEF"},
        {"name": "D. Ćaleta-Car", "rating": 74, "pos": "DEF"}, {"name": "Sergio Gómez", "rating": 78, "pos": "DEF/MID"},
        {"name": "Aihen Muñoz", "rating": 74, "pos": "DEF"}, {"name": "Turrientes", "rating": 76, "pos": "MID"},
        {"name": "Gorrotxa", "rating": 76, "pos": "MID"}, {"name": "Carlos Soler", "rating": 78, "pos": "MID"}, {"name": "Pablo Marín", "rating": 73, "pos": "MID"},
        {"name": "L. Sučić", "rating": 76, "pos": "MID"}, {"name": "Brais Méndez", "rating": 78, "pos": "MID"},
        {"name": "Y. Herrera", "rating": 80, "pos": "MID"}, {"name": "Guedes", "rating": 78, "pos": "FWD/MID"},
        {"name": "T. Kubo", "rating": 81, "pos": "FWD/MID"}, {"name": "A. Zakharyan", "rating": 73, "pos": "FWD/MID"},
        {"name": "Barrenetxea", "rating": 78, "pos": "FWD/MID"}, {"name": "Wesley", "rating": 69, "pos": "FWD/MID"},
        {"name": "Oyarzabal", "rating": 83, "pos": "FWD"}, {"name": "O. Óskarsson", "rating": 74, "pos": "FWD"},
        {"name": "Karrikaburu", "rating": 67, "pos": "FWD"}
    ]},

        "Villarreal": {"emoji": "🟡", "players": [
        {"name": "Luiz Júnior", "rating": 78, "pos": "GK"}, {"name": "Arnau", "rating": 75, "pos": "GK"},
        {"name": "S. Mouriño", "rating": 78, "pos": "DEF"}, {"name": "A. Freeman", "rating": 73, "pos": "DEF"},
        {"name": "Pau Navarro", "rating": 71, "pos": "DEF"}, {"name": "Rafa Marín", "rating": 76, "pos": "DEF"},
        {"name": "W. Kambwala", "rating": 72, "pos": "DEF"}, {"name": "J. Foyth", "rating": 79, "pos": "DEF"},
        {"name": "L. Costa", "rating": 77, "pos": "DEF"}, {"name": "Renato Veiga", "rating": 78, "pos": "DEF/MID"},
        {"name": "J. Valou", "rating": 62, "pos": "DEF"}, {"name": "Pedraza", "rating": 76, "pos": "DEF/MID"},
        {"name": "Sergi Cardona", "rating": 79, "pos": "DEF"}, {"name": "Santi Comesaña", "rating": 78, "pos": "MID"},
        {"name": "Parejo", "rating": 80, "pos": "MID"}, {"name": "P. Gueye", "rating": 80, "pos": "MID"}, {"name": "Partey", "rating": 79, "pos": "MID"},
        {"name": "A. Diatta", "rating": 63, "pos": "MID/FWD"}, {"name": "N. Pépé", "rating": 81, "pos": "FWD/MID"},
        {"name": "T. Buchanan", "rating": 76, "pos": "FWD/MID"}, {"name": "Moleiro", "rating": 81, "pos": "MID/FWD"},
        {"name": "Alfon", "rating": 75, "pos": "FWD/MID"}, {"name": "G. Mikautadze", "rating": 79, "pos": "FWD"},
        {"name": "Gerard Moreno", "rating": 81, "pos": "FWD"}, {"name": "Ayoze", "rating": 81, "pos": "FWD"}
    ]},

        "Real Betis": {"emoji": "🟢⚪", "players": [
        {"name": "Álvaro Valles", "rating": 78, "pos": "GK"}, {"name": "Pau López", "rating": 78, "pos": "GK"}, {"name": "Adrián", "rating": 71, "pos": "GK"},
        {"name": "Aitor Ruibal", "rating": 77, "pos": "DEF"}, {"name": "Héctor Bellerín", "rating": 76, "pos": "DEF"},
        {"name": "Bartra", "rating": 79, "pos": "DEF"}, {"name": "Diego Llorente", "rating": 80, "pos": "DEF"},
        {"name": "Natan", "rating": 78, "pos": "DEF"}, {"name": "V. Gómez", "rating": 76, "pos": "DEF"},
        {"name": "R. Rodríguez", "rating": 73, "pos": "DEF"}, {"name": "Junior Firpo", "rating": 74, "pos": "DEF"},
        {"name": "Marc Roca", "rating": 78, "pos": "MID"}, {"name": "Altimira", "rating": 77, "pos": "MID"}, {"name": "Nelson Deossa", "rating": 75, "pos": "MID"},
        {"name": "S. Amrabat", "rating": 79, "pos": "MID"}, {"name": "G. Lo Celso", "rating": 81, "pos": "MID"}, {"name": "Isco", "rating": 84, "pos": "MID"},
        {"name": "Fornals", "rating": 81, "pos": "MID"}, {"name": "Fidalgo", "rating": 78, "pos": "MID"},
        {"name": "Antony", "rating": 81, "pos": "FWD/MID"}, {"name": "Pablo García", "rating": 70, "pos": "FWD/MID"},
        {"name": "Abde", "rating": 80, "pos": "FWD/MID"}, {"name": "Riquelme", "rating": 76, "pos": "FWD/MID"},
        {"name": "Cucho Hernández", "rating": 79, "pos": "FWD"}, {"name": "C. Bakambu", "rating": 75, "pos": "FWD"},
        {"name": "Chimy Ávila", "rating": 73, "pos": "FWD"}
    ]},

        "RB Leipzig": {"emoji": "⚪🔴", "players": [
        {"name": "M. Vandevoordt", "rating": 76, "pos": "GK"}, {"name": "L. Zingerle", "rating": 69, "pos": "GK"},
        {"name": "Gulácsi", "rating": 85, "pos": "GK"},
        {"name": "R. Baku", "rating": 79, "pos": "DEF"}, {"name": "B. Henrichs", "rating": 80, "pos": "DEF"},
        {"name": "W. Orban", "rating": 83, "pos": "DEF"}, {"name": "L. Klostermann", "rating": 76, "pos": "DEF"},
        {"name": "C. Lukeba", "rating": 81, "pos": "DEF"}, {"name": "E. Bitshiabu", "rating": 75, "pos": "DEF"},
        {"name": "D. Raum", "rating": 83, "pos": "DEF/MID"}, {"name": "M. Finkgräfe", "rating": 69, "pos": "DEF/MID"}, {"name": "Ouédraogo", "rating": 73, "pos": "DEF/MID"},
        {"name": "N. Seiwald", "rating": 80, "pos": "MID"}, {"name": "Xaver Schlager", "rating": 78, "pos": "MID"},
        {"name": "B. Gruda", "rating": 75, "pos": "MID/FWD"}, {"name": "E. Banzuzi", "rating": 73, "pos": "MID/FWD"},
        {"name": "C. Baumgartner", "rating": 81, "pos": "MID/FWD"}, {"name": "Y. Diomandé", "rating": 80, "pos": "FWD/MID"},
        {"name": "J. Bakayoko", "rating": 77, "pos": "FWD/MID"}, {"name": "A. Maksimović", "rating": 71, "pos": "FWD/MID"},
        {"name": "A. Nusa", "rating": 78, "pos": "FWD/MID"}, {"name": "S. Sani", "rating": 68, "pos": "FWD/MID"},
        {"name": "Rômulo", "rating": 78, "pos": "FWD"}, {"name": "C. Harder", "rating": 75, "pos": "FWD"}
    ]},

        "Stuttgart": {"emoji": "⚪🔴", "players": [
        {"name": "Nübel", "rating": 81, "pos": "GK"}, {"name": "Bredlow", "rating": 71, "pos": "GK"},
        {"name": "L. Assignon", "rating": 75, "pos": "DEF"}, {"name": "J. Vagnoman", "rating": 75, "pos": "DEF"}, {"name": "Al Dakhil", "rating": 72, "pos": "DEF"},
        {"name": "F. Jeltsch", "rating": 73, "pos": "DEF"}, {"name": "Jaquez", "rating": 71, "pos": "DEF"}, {"name": "Zagadou", "rating": 74, "pos": "DEF"},
        {"name": "J. Chabot", "rating": 80, "pos": "DEF"}, {"name": "R. Hendriks", "rating": 73, "pos": "DEF"},
        {"name": "D. Zagadou", "rating": 74, "pos": "DEF"}, {"name": "M. Herwerth", "rating": 63, "pos": "DEF"},
        {"name": "M. Mittelstädt", "rating": 83, "pos": "DEF/MID"}, {"name": "A. Stiller", "rating": 83, "pos": "MID"},
        {"name": "A. Karazor", "rating": 76, "pos": "MID"}, {"name": "Nartey", "rating": 72, "pos": "MID"},
        {"name": "Chema Amo", "rating": 72, "pos": "MID"}, {"name": "D. Undav", "rating": 82, "pos": "MID/FWD"},
        {"name": "B. El Khannouss", "rating": 78, "pos": "MID/FWD"}, {"name": "J. Leweling", "rating": 78, "pos": "FWD/MID"},
        {"name": "B. Bouanani", "rating": 75, "pos": "FWD/MID"}, {"name": "C. Führich", "rating": 76, "pos": "FWD/MID"},
        {"name": "Tiago Tomás", "rating": 76, "pos": "FWD/MID"}, {"name": "E. Demirović", "rating": 80, "pos": "FWD"},
        {"name": "Jeremy", "rating": 66, "pos": "FWD"}
    ]},

        "Eintracht Frankfurt": {"emoji": "🦅", "players": [
        {"name": "Zetterer", "rating": 76, "pos": "GK"}, {"name": "Kauã Santos", "rating": 71, "pos": "GK"},
        {"name": "N. Collins", "rating": 74, "pos": "DEF"}, {"name": "T. Chandler", "rating": 64, "pos": "DEF"},
        {"name": "R. Kristensen", "rating": 79, "pos": "DEF"}, {"name": "E. Baum", "rating": 72, "pos": "DEF"},
        {"name": "R. Koch", "rating": 80, "pos": "DEF"}, {"name": "A. Amenda", "rating": 73, "pos": "DEF"},
        {"name": "A. Theate", "rating": 79, "pos": "DEF"},
        {"name": "N. Brown", "rating": 79, "pos": "DEF/MID"}, {"name": "K. Kosugi", "rating": 71, "pos": "DEF/MID"},
        {"name": "H. Larsson", "rating": 77, "pos": "MID"}, {"name": "E. Skhiri", "rating": 77, "pos": "MID"},
        {"name": "F. Chaïbi", "rating": 76, "pos": "MID/FWD"}, {"name": "R. Doan", "rating": 81, "pos": "MID/FWD"},
        {"name": "M. Dahoud", "rating": 73, "pos": "MID"}, {"name": "O. Højlund", "rating": 73, "pos": "MID"},
        {"name": "M. Götze", "rating": 79, "pos": "MID/FWD"},
        {"name": "J. Bahoya", "rating": 75, "pos": "FWD/MID"}, {"name": "A. Knauff", "rating": 77, "pos": "FWD/MID"},
        {"name": "A. Kalimuendo", "rating": 77, "pos": "FWD/MID"}, {"name": "A. Amaime", "rating": 68, "pos": "FWD/MID"},
        {"name": "J. Burkardt", "rating": 82, "pos": "FWD"}, {"name": "C. Uzun", "rating": 78, "pos": "FWD/MID"},
        {"name": "Y. Ebnoutalib", "rating": 70, "pos": "FWD"}, {"name": "M. Batshuayi", "rating": 75, "pos": "FWD"},
    ]},

        "AS Roma": {"emoji": "🐺🟡🔴", "players": [
        {"name": "M. Svilar", "rating": 84, "pos": "GK"}, {"name": "P. Gollini", "rating": 74, "pos": "GK"},
        {"name": "G. Mancini", "rating": 84, "pos": "DEF"}, {"name": "E. Ndicka", "rating": 81, "pos": "DEF"},
        {"name": "D. Rensch", "rating": 74, "pos": "DEF"}, {"name": "J. Ziółkowski", "rating": 69, "pos": "DEF"},
        {"name": "D. Ghilardi", "rating": 72, "pos": "DEF"}, {"name": "Mario Hermoso", "rating": 79, "pos": "DEF"},
        {"name": "Z. Çelik", "rating": 78, "pos": "DEF/MID"},
        {"name": "K. Koné", "rating": 80, "pos": "MID"}, {"name": "B. Cristante", "rating": 81, "pos": "MID"},
        {"name": "N. El Aynaoui", "rating": 76, "pos": "MID"}, {"name": "L. Pellegrini", "rating": 80, "pos": "MID/FWD"},
        {"name": "P. Dybala", "rating": 85, "pos": "MID/FWD"}, {"name": "Wesley", "rating": 78, "pos": "DEF/MID/FWD"},
        {"name": "Bryan Zaragoza", "rating": 77, "pos": "MID/FWD"}, {"name": "S. El Shaarawy", "rating": 78, "pos": "MID/FWD"},
        {"name": "Angeliño", "rating": 79, "pos": "DEF/MID/FWD"}, {"name": "K. Tsimikas", "rating": 77, "pos": "MID/FWD"},
        {"name": "M. Soulé", "rating": 79, "pos": "FWD/MID"}, {"name": "D. Malen", "rating": 79, "pos": "FWD"},
        {"name": "E. Ferguson", "rating": 74, "pos": "FWD"},
        {"name": "A. Dovbyk", "rating": 81, "pos": "FWD"}, {"name": "R. Vaz", "rating": 70, "pos": "FWD"}
    ]},

        "Atalanta": {"emoji": "🟦⬛", "players": [
        {"name": "M. Carnesecchi", "rating": 85, "pos": "GK"}, {"name": "M. Sportiello", "rating": 76, "pos": "GK"},
        {"name": "G. Scalvini", "rating": 78, "pos": "DEF"}, {"name": "B. Djimsiti", "rating": 79, "pos": "DEF"},
        {"name": "I. Hien", "rating": 78, "pos": "DEF"}, {"name": "H. Ahanor", "rating": 72, "pos": "DEF"},
        {"name": "O. Kossounou", "rating": 80, "pos": "DEF"}, {"name": "R. Obrić", "rating": 65, "pos": "DEF"},
        {"name": "S. Kolašinac", "rating": 78, "pos": "DEF"}, {"name": "D. Zappacosta", "rating": 79, "pos": "DEF/MID"},
        {"name": "R. Bellanova", "rating": 78, "pos": "DEF/MID"}, {"name": "M. Pašalić", "rating": 79, "pos": "MID"},
        {"name": "M. de Roon", "rating": 81, "pos": "MID"}, {"name": "Éderson", "rating": 82, "pos": "MID"},
        {"name": "Y. Musah", "rating": 74, "pos": "MID"}, {"name": "N. Zalewski", "rating": 77, "pos": "MID/FWD"},
        {"name": "C. De Ketelaere", "rating": 82, "pos": "MID/FWD"}, {"name": "L. Samardžić", "rating": 76, "pos": "MID/FWD"},
        {"name": "K. Sulemana", "rating": 72, "pos": "MID/FWD"}, {"name": "L. Bernasconi", "rating": 70, "pos": "FWD/MID"},
        {"name": "M. Bakker", "rating": 75, "pos": "FWD/MID"}, {"name": "N. Krstović", "rating": 76, "pos": "FWD"},
        {"name": "G. Scamacca", "rating": 78, "pos": "FWD"}, {"name": "G. Raspadori", "rating": 78, "pos": "FWD"}
    ]},

        "Olympique de Marseille": {"emoji": "⚪🔵", "players": [
        {"name": "G. Rulli", "rating": 81, "pos": "GK"}, {"name": "J. de Lange", "rating": 74, "pos": "GK"},
        {"name": "B. Pavard", "rating": 81, "pos": "DEF"}, {"name": "C. Egan-Riley", "rating": 75, "pos": "DEF"},
        {"name": "L. Balerdi", "rating": 80, "pos": "DEF"}, {"name": "N. Aguerd", "rating": 81, "pos": "DEF"},
        {"name": "T. Weah", "rating": 77, "pos": "DEF/MID"}, {"name": "F. Medina", "rating": 79, "pos": "DEF/MID"},
        {"name": "Emerson", "rating": 77, "pos": "DEF/MID"}, {"name": "P. Højbjerg", "rating": 81, "pos": "MID"},
        {"name": "G. Kondogbia", "rating": 77, "pos": "MID"}, {"name": "A. Vermeeren", "rating": 77, "pos": "MID"},
        {"name": "Q. Timber", "rating": 80, "pos": "MID"}, {"name": "H. Abdelli", "rating": 77, "pos": "MID/FWD"},
        {"name": "B. Nadir", "rating": 73, "pos": "MID/FWD"}, {"name": "E. Nwaneri", "rating": 76, "pos": "MID/FWD"},
        {"name": "M. Greenwood", "rating": 83, "pos": "FWD/MID"}, {"name": "Igor Paixão", "rating": 80, "pos": "FWD/MID"},
        {"name": "H. Traoré", "rating": 77, "pos": "FWD/MID"}, {"name": "P. Aubameyang", "rating": 81, "pos": "FWD"},
        {"name": "A. Gouiri", "rating": 79, "pos": "FWD"}
    ]},

        "Olympique Lyonnais": {"emoji": "🦁🔴🔵", "players": [
        {"name": "D. Greif", "rating": 79, "pos": "GK"}, {"name": "R. Descamps", "rating": 75, "pos": "GK"},
        {"name": "M. Niakhaté", "rating": 80, "pos": "DEF"}, {"name": "Clinton Mata", "rating": 76, "pos": "DEF"},
        {"name": "R. Kluivert", "rating": 72, "pos": "DEF"},
        {"name": "H. Hateboer", "rating": 74, "pos": "DEF"}, {"name": "A. Maitland-Niles", "rating": 77, "pos": "DEF/MID"},
        {"name": "N. Tagliafico", "rating": 78, "pos": "DEF/MID"},
        {"name": "Abner Vinícius", "rating": 74, "pos": "DEF/MID"}, {"name": "C. Tolisso", "rating": 82, "pos": "MID"},
        {"name": "T. Tessmann", "rating": 76, "pos": "MID"}, {"name": "T. Morton", "rating": 78, "pos": "MID"},
        {"name": "O. Mangala", "rating": 76, "pos": "MID"}, {"name": "N. Nartey", "rating": 69, "pos": "MID"},
        {"name": "K. Merah", "rating": 70, "pos": "MID"},
        {"name": "Endrick", "rating": 78, "pos": "FWD/MID"}, {"name": "A. Karabec", "rating": 73, "pos": "FWD/MID"},
        {"name": "R. Ghezzal", "rating": 72, "pos": "FWD/MID"}, {"name": "E. Nuamah", "rating": 75, "pos": "FWD/MID"},
        {"name": "Afonso Moreira", "rating": 75, "pos": "FWD/MID"}, {"name": "M. Fofana", "rating": 78, "pos": "FWD/MID"},
        {"name": "P. Šulc", "rating": 78, "pos": "FWD"}, {"name": "R. Yaremchuk", "rating": 74, "pos": "FWD"}
    ]},

        "PSV": {"emoji": "🔴⚪", "players": [
        {"name": "M. Kovář", "rating": 76, "pos": "GK"}, {"name": "Olij", "rating": 76, "pos": "GK"},
        {"name": "A. Obispo", "rating": 74, "pos": "DEF"}, {"name": "Yarek", "rating": 76, "pos": "DEF"},
        {"name": "J. Schouten", "rating": 79, "pos": "DEF"}, {"name": "R. Flamingo", "rating": 76, "pos": "DEF"},
        {"name": "K. Sildillia", "rating": 72, "pos": "DEF/MID"}, {"name": "S. Dest", "rating": 79, "pos": "DEF/MID"},
        {"name": "Mauro Júnior", "rating": 80, "pos": "DEF/MID"}, {"name": "A. Salah-Eddine", "rating": 75, "pos": "DEF/MID"},
        {"name": "J. Veerman", "rating": 81, "pos": "MID"}, {"name": "I. Saibari", "rating": 80, "pos": "MID"},
        {"name": "P. Wanner", "rating": 74, "pos": "MID"}, {"name": "D. Man", "rating": 77, "pos": "FWD/MID"},
        {"name": "E. Bajraktarević", "rating": 71, "pos": "FWD/MID"}, {"name": "I. Perišić", "rating": 81, "pos": "FWD/MID"},
        {"name": "C. Driouech", "rating": 72, "pos": "FWD/MID"}, {"name": "N. Fernandez", "rating": 61, "pos": "FWD/MID"},
        {"name": "R. van Bommel", "rating": 74, "pos": "FWD/MID"}, {"name": "G. Til", "rating": 77, "pos": "FWD"},
        {"name": "M. Boadu", "rating": 74, "pos": "FWD"}, {"name": "R. Pepi", "rating": 76, "pos": "FWD"},
        {"name": "A. Pléa", "rating": 78, "pos": "FWD"}
    ]},

        "Sporting CP": {"emoji": "🦁🟢⚪", "players": [
        {"name": "Rui Silva", "rating": 81, "pos": "GK"}, {"name": "João Virgínia", "rating": 72, "pos": "GK"},
        {"name": "Gonçalo Inácio", "rating": 81, "pos": "DEF"}, {"name": "O. Diomande", "rating": 80, "pos": "DEF"},
        {"name": "Z. Debast", "rating": 78, "pos": "DEF"}, {"name": "Eduardo Quaresma", "rating": 77, "pos": "DEF"},
        {"name": "M. Araújo", "rating": 78, "pos": "DEF/MID"},
        {"name": "Fresneda", "rating": 74, "pos": "DEF/MID"}, {"name": "G. Vagiannidis", "rating": 75, "pos": "DEF/MID"},
        {"name": "H. Morita", "rating": 78, "pos": "MID"}, {"name": "M. Hjulmand", "rating": 83, "pos": "MID"},
        {"name": "G. Kochorashvili", "rating": 74, "pos": "MID"}, {"name": "Trincão", "rating": 83, "pos": "MID/FWD"},
        {"name": "João Simões", "rating": 70, "pos": "MID/FWD"}, {"name": "Daniel Bragança", "rating": 77, "pos": "MID/FWD"},
        {"name": "Flávio Goncalves", "rating": 65, "pos": "MID/FWD"}, {"name": "Geny Catamo", "rating": 78, "pos": "FWD/MID"},
        {"name": "Geovany Quenda", "rating": 76, "pos": "FWD/MID"}, {"name": "Luis Guilherme", "rating": 71, "pos": "FWD/MID"},
        {"name": "Salvador Agra", "rating": 67, "pos": "FWD/MID"}, {"name": "Pedro Gonçalves", "rating": 83, "pos": "FWD/MID"},
        {"name": "Nuno Santos", "rating": 77, "pos": "FWD/MID"}, {"name": "Ricardo Mangas", "rating": 74, "pos": "FWD/MID"},
        {"name": "S. Faye", "rating": 68, "pos": "FWD/MID"}, {"name": "L. Suárez", "rating": 80, "pos": "FWD"},
        {"name": "F. Ioannidis", "rating": 77, "pos": "FWD"}
    ]},

        "FC Porto": {"emoji": "🐉🔵⚪", "players": [
        {"name": "Diogo Costa", "rating": 84, "pos": "GK"}, {"name": "Cláudio Ramos", "rating": 73, "pos": "GK"},
        {"name": "J. Kiwior", "rating": 80, "pos": "DEF"}, {"name": "D. Prpić", "rating": 73, "pos": "DEF"},
        {"name": "J. Bednarek", "rating": 79, "pos": "DEF"}, {"name": "Thiago Silva", "rating": 82, "pos": "DEF"},
        {"name": "N. Pérez", "rating": 76, "pos": "DEF"}, {"name": "Alberto Costa", "rating": 76, "pos": "DEF/MID"},
        {"name": "Martim Fernandes", "rating": 76, "pos": "DEF"}, {"name": "Francisco Moura", "rating": 77, "pos": "DEF"},
        {"name": "Z. Sanusi", "rating": 70, "pos": "DEF/MID"}, {"name": "A. Varela", "rating": 80, "pos": "MID"},
        {"name": "P. Rosario", "rating": 78, "pos": "MID"}, {"name": "Gabri Veiga", "rating": 79, "pos": "MID"},
        {"name": "V. Froholdt", "rating": 78, "pos": "MID"}, {"name": "S. Fofana", "rating": 76, "pos": "MID"},
        {"name": "Pepê", "rating": 78, "pos": "MID"}, {"name": "William Gomes", "rating": 75, "pos": "FWD/MID"},
        {"name": "B. Caicedo", "rating": 61, "pos": "MID"}, {"name": "Y. Karamoh", "rating": 72, "pos": "FWD/MID"},
        {"name": "Borja Sainz", "rating": 78, "pos": "FWD/MID"}, {"name": "Rodrigo Mora", "rating": 77, "pos": "FWD"},
        {"name": "D. Gül", "rating": 70, "pos": "FWD"}, {"name": "T. Moffi", "rating": 74, "pos": "FWD"},
        {"name": "Samu", "rating": 79, "pos": "FWD"}, {"name": "L. de Jong", "rating": 78, "pos": "FWD"}
    ]},

        "SL Benfica": {"emoji": "🦅🔴⚪", "players": [
        {"name": "A. Trubin", "rating": 80, "pos": "GK"}, {"name": "Samuel Soares", "rating": 70, "pos": "GK"},
        {"name": "N. Otamendi", "rating": 81, "pos": "DEF"},
        {"name": "António Silva", "rating": 77, "pos": "DEF"}, {"name": "Tomás Araújo", "rating": 72, "pos": "DEF"},
        {"name": "A. Dedić", "rating": 75, "pos": "DEF"}, {"name": "A. Bah", "rating": 77, "pos": "DEF/MID"},
        {"name": "S. Dahl", "rating": 75, "pos": "DEF"},
        {"name": "E. Barrenechea", "rating": 77, "pos": "MID"}, {"name": "R. Ríos", "rating": 78, "pos": "MID"},
        {"name": "L. Barreiro", "rating": 76, "pos": "MID"}, {"name": "João Veloso", "rating": 65, "pos": "MID"},
        {"name": "Manu Silva", "rating": 72, "pos": "MID"},
        {"name": "Diogo Prioste", "rating": 66, "pos": "MID"}, {"name": "Rafa", "rating": 82, "pos": "MID/FWD"},
        {"name": "G. Sudakov", "rating": 80, "pos": "MID/FWD"}, {"name": "F. Aursnes", "rating": 80, "pos": "FWD/MID"},
        {"name": "D. Lukébakio", "rating": 82, "pos": "FWD/MID"}, {"name": "G. Prestianni", "rating": 72, "pos": "FWD/MID"},
        {"name": "A. Schjelderup", "rating": 76, "pos": "FWD/MID"},
        {"name": "Bruma", "rating": 78, "pos": "FWD"}, {"name": "V. Pavlidis", "rating": 83, "pos": "FWD"},
        {"name": "F. Ivanović", "rating": 74, "pos": "FWD"}
    ]},

        "Fulham": {"emoji": "⚪⚫", "players": [ 
        {"name": "Leno", "rating": 79, "pos": "GK"}, {"name": "Lecomte", "rating": 74, "pos": "GK"},
        {"name": "Tete", "rating": 78, "pos": "DEF"}, {"name": "Castagne", "rating": 75, "pos": "DEF"},
        {"name": "Andersen", "rating": 79, "pos": "DEF"}, {"name": "Diop", "rating": 76, "pos": "DEF"},
        {"name": "Bassey", "rating": 78, "pos": "DEF"}, {"name": "Jorge Cuenca", "rating": 76, "pos": "DEF"},
        {"name": "Sessegnon", "rating": 77, "pos": "DEF"}, {"name": "Robinson", "rating": 82, "pos": "DEF"},
        {"name": "Berge", "rating": 79, "pos": "MID"}, {"name": "Reed", "rating": 72, "pos": "MID"},
        {"name": "Lukić", "rating": 78, "pos": "MID"}, {"name": "Cairney", "rating": 74, "pos": "MID"},
        {"name": "Smith Rowe", "rating": 77, "pos": "MID"}, {"name": "King", "rating": 74, "pos": "MID"},
        {"name": "Wilson", "rating": 79, "pos": "FWD"}, {"name": "Bobb", "rating": 76, "pos": "FWD"},
        {"name": "Chukwueze", "rating": 80, "pos": "FWD"}, {"name": "Iwobi", "rating": 80, "pos": "FWD"},
        {"name": "Kevin", "rating": 76, "pos": "FWD"}, {"name": "Jiménez", "rating": 78, "pos": "FWD"},
        {"name": "Rodrigo", "rating": 76, "pos": "FWD"}
    ],

        "Sunderland": {"emoji": "🔴⚪", "players": [
        {"name": "Roefs", "rating": 79, "pos": "GK"}, {"name": "Ellborg", "rating": 64, "pos": "GK"},
        {"name": "Mukiele", "rating": 80, "pos": "DEF"}, {"name": "Ballard", "rating": 78, "pos": "DEF"}, {"name": "Cirkin", "rating": 72, "pos": "DEF"},
        {"name": "Geertruida", "rating": 78, "pos": "DEF"}, {"name": "Alderete", "rating": 80, "pos": "DEF"}, {"name": "O'Nien", "rating": 72, "pos": "DEF"},
        {"name": "Hume", "rating": 78, "pos": "DEF"}, {"name": "Reinildo", "rating": 80, "pos": "DEF"},
        {"name": "Xhaka", "rating": 85, "pos": "MID"}, {"name": "Sadiki", "rating": 77, "pos": "MID"},
        {"name": "Rigg", "rating": 72, "pos": "MID"}, {"name": "Diarra", "rating": 77, "pos": "MID"},
        {"name": "Aleksić", "rating": 61, "pos": "MID"}, {"name": "Talbi", "rating": 76, "pos": "MID"},
        {"name": "Ba", "rating": 65, "pos": "MID"}, {"name": "Traoré", "rating": 75, "pos": "MID"}, {"name": "Angulo", "rating": 75, "pos": "MID"},
        {"name": "Ta Bi", "rating": 68, "pos": "MID"}, {"name": "Le Fée", "rating": 78, "pos": "MID"},
        {"name": "Mundle", "rating": 71, "pos": "FWD"}, {"name": "Brobbey", "rating": 77, "pos": "FWD"},
        {"name": "Isidor", "rating": 75, "pos": "FWD"},{"name": "Mayenda", "rating": 72, "pos": "FWD"},
    ],

  },


}
}


    #     "Celta Vigo": {"emoji": "🩵", "players": [
    #     {"name": "Radu", "rating": 78, "pos": "GK"}, {"name": "Iván Villar", "rating": 72, "pos": "GK"},
    #     {"name": "Starfelt", "rating": 78, "pos": "DEF"}, {"name": "Aidoo", "rating": 73, "pos": "DEF"},
    #     {"name": "Manu Sánchez", "rating": 70, "pos": "DEF"}, {"name": "Carlos Domínguez", "rating": 73, "pos": "DEF"},
    #     {"name": "Yoel Lago", "rating": 71, "pos": "DEF"}, {"name": "Marcos Alonso", "rating": 79, "pos": "DEF"},
    #     {"name": "Javi Rueda", "rating": 74, "pos": "DEF/MID"}, {"name": "El-Abde", "rating": 70, "pos": "MID"},
    #     {"name": "Javi Rodríguez", "rating": 66, "pos": "DEF"}, {"name": "Mingueza", "rating": 80, "pos": "DEF/MID"},
    #     {"name": "Hugo Álvarez", "rating": 75, "pos": "DEF/MID"}, {"name": "Carreira", "rating": 75, "pos": "DEF/MID"},
    #     {"name": "Álvaro Núñez", "rating": 76, "pos": "DEF/MID"}, {"name": "Moriba", "rating": 78, "pos": "MID"},
    #     {"name": "Hugo Sotelo", "rating": 74, "pos": "MID"}, {"name": "Vecino", "rating": 76, "pos": "MID"},
    #     {"name": "Swedberg", "rating": 75, "pos": "MID/FWD"}, {"name": "Fer López", "rating": 73, "pos": "MID/FWD"},
    #     {"name": "Borja Iglesias", "rating": 80, "pos": "FWD"}, {"name": "Iago Aspas", "rating": 82, "pos": "FWD"},
    #     {"name": "Ferran Jutglà", "rating": 75, "pos": "FWD"}, {"name": "Pablo Durán", "rating": 74, "pos": "FWD"}
    # ]},

#         "Brentford": {"emoji": "🐝", "players": [
#         {"name": "Kelleher", "rating": 79, "pos": "GK"}, {"name": "Valdimarsson", "rating": 69, "pos": "GK"},
#         {"name": "Kayode", "rating": 80, "pos": "DEF"}, {"name": "Hickey", "rating": 75, "pos": "DEF"},
#         { "name": "Ajer", "rating": 76, "pos": "DEF"}, {"name": "Collins", "rating": 79, "pos": "DEF"},
#         {"name": "van den Berg", "rating": 77, "pos": "DEF"}, {"name": "Pinnock", "rating": 75, "pos": "DEF"},
#         {"name": "Henry", "rating": 76, "pos": "DEF"}, {"name": "Lewis-Potter", "rating": 76, "pos": "DEF"},
#         {"name": "Yarmoliuk", "rating": 77, "pos": "MID"}, {"name": "Henderson", "rating": 79, "pos": "MID"},
#         {"name": "Janelt", "rating": 77, "pos": "MID"}, {"name": "Dasilva", "rating": 72, "pos": "MID"},
#         {"name": "Jensen", "rating": 79, "pos": "MID"}, {"name": "Damsgaard", "rating": 80, "pos": "MID"},
#         {"name": "Fábio Carvalho", "rating": 74, "pos": "MID"}, {"name": "Milambo", "rating": 73, "pos": "MID"},
#         {"name": "Ouattara", "rating": 78, "pos": "FWD"}, {"name": "Donovan", "rating": 65, "pos": "FWD"},
#         {"name": "Schade", "rating": 79, "pos": "FWD"}, {"name": "Igor Thiago", "rating": 81, "pos": "FWD"},
#         {"name": "Furo", "rating": 63, "pos": "FWD"}, {"name": "Nelson", "rating": 75, "pos": "FWD"},
#     ]},

#         "Forest": {"emoji": "🌳", "players": [
#         {"name": "Sels", "rating": 82, "pos": "GK"}, {"name": "Ortega", "rating": 79, "pos": "GK"},
#         {"name": "Aina", "rating": 80, "pos": "DEF"}, {"name": "da Silva Santos", "rating": 61, "pos": "DEF"}, {"name": "Boly", "rating": 73, "pos": "DEF"},
#         {"name": "Milenkovic", "rating": 81, "pos": "DEF"}, {"name": "Jair Cunha", "rating": 74, "pos": "DEF"}, {"name": "Savona", "rating": 75, "pos": "DEF"},
#         {"name": "Murillo", "rating": 82, "pos": "DEF"}, {"name": "Morato", "rating": 76, "pos": "DEF"},
#         {"name": "Williams", "rating": 80, "pos": "DEF"}, {"name": "Netz", "rating": 73, "pos": "DEF"},
#         {"name": "Sangaré", "rating": 78, "pos": "MID"}, {"name": "Domínguez", "rating": 78, "pos": "MID"}, {"name": "Yates", "rating": 76, "pos": "MID"},
#         {"name": "Anderson", "rating": 82, "pos": "MID"}, {"name": "Gibbs-White", "rating": 81, "pos": "MID"},
#         {"name": "Hutchinson", "rating": 76, "pos": "FWD"}, {"name": "Bakwa", "rating": 76, "pos": "FWD"},
#         {"name": "Hudson-Odoi", "rating": 78, "pos": "FWD"}, {"name": "Ndoye", "rating": 77, "pos": "FWD"},
#         {"name": "Igor Jesus", "rating": 77, "pos": "FWD"}, {"name": "Lucca", "rating": 75, "pos": "FWD"},
#         {"name": "Awoniyi", "rating": 74, "pos": "FWD"}, {"name": "Wood", "rating": 81, "pos": "FWD"}
#     ]},

#         "Everton": {"emoji": "🔵", "players": [
#         {"name": "Pickford", "rating": 84, "pos": "GK"}, {"name": "Travers", "rating": 72, "pos": "GK"},
#         {"name": "O'Brien", "rating": 76, "pos": "DEF"}, {"name": "Patterson", "rating": 71, "pos": "DEF"},
#         {"name": "Tarkowski", "rating": 80, "pos": "DEF"}, {"name": "Keane", "rating": 76, "pos": "DEF"}, {"name": "Coleman", "rating": 70, "pos": "DEF"},
#         {"name": "Branthwaite", "rating": 79, "pos": "DEF"}, {"name": "Mykolenko", "rating": 77, "pos": "DEF"},
#         {"name": "Aznou", "rating": 66, "pos": "DEF"}, {"name": "Garner", "rating": 80, "pos": "MID"}, {"name": "Armstrong", "rating": 73, "pos": "MID"},
#         {"name": "Iroegbunam", "rating": 76, "pos": "MID"}, {"name": "Gueye", "rating": 79, "pos": "MID"},
#         {"name": "Dewsbury-Hall", "rating": 79, "pos": "MID"}, {"name": "Alcaraz", "rating": 75, "pos": "MID"},
#         {"name": "Röhl", "rating": 74, "pos": "MID"}, {"name": "Ndiaye", "rating": 82, "pos": "FWD"},
#         {"name": "Dibling", "rating": 74, "pos": "FWD"}, {"name": "McNeil", "rating": 77, "pos": "FWD"},
#         {"name": "George", "rating": 71, "pos": "FWD"}, {"name": "Barry", "rating": 76, "pos": "FWD"},
#         {"name": "Beto", "rating": 76, "pos": "FWD"}, {"name": "Grealish", "rating": 82, "pos": "FWD"}
#     ]},


#         "Bournemouth": {"emoji": "🍒", "players": [
#         {"name": "Petrović", "rating": 79, "pos": "GK"}, {"name": "Forster", "rating": 72, "pos": "GK"},
#         {"name": "Álex Jiménez", "rating": 77, "pos": "DEF"}, {"name": "Smith", "rating": 73, "pos": "DEF"},
#         {"name": "Hill", "rating": 74, "pos": "DEF"}, {"name": "Diakité", "rating": 72, "pos": "DEF"},
#         {"name": "Senesi", "rating": 80, "pos": "DEF"}, {"name": "Milosavljevic", "rating": 71, "pos": "DEF"},
#         {"name": "Truffert", "rating": 79, "pos": "DEF"}, {"name": "Soler", "rating": 68, "pos": "DEF"},
#         {"name": "Scott", "rating": 79, "pos": "MID"}, {"name": "Cook", "rating": 78, "pos": "MID"}, {"name": "Gannon-Doak", "rating": 71, "pos": "MID"},
#         {"name": "Adams", "rating": 79, "pos": "MID"}, {"name": "Christie", "rating": 78, "pos": "MID"}, {"name": "Tóth", "rating": 72, "pos": "MID"},
#         {"name": "Kroupi", "rating": 78, "pos": "MID"}, {"name": "Kluivert", "rating": 79, "pos": "MID"},
#         {"name": "Rayan", "rating": 77, "pos": "FWD"}, {"name": "Brooks", "rating": 76, "pos": "FWD"},
#         {"name": "Adli", "rating": 77, "pos": "FWD"}, {"name": "Tavernier", "rating": 78, "pos": "FWD"},
#         {"name": "Evanilson", "rating": 80, "pos": "FWD"}, {"name": "Ünal", "rating": 76, "pos": "FWD"}
#     ]},
    
#         "Crystal Palace": {"emoji": "🦅", "players": [
#         {"name": "Henderson", "rating": 82, "pos": "GK"}, {"name": "Benítez", "rating": 78, "pos": "GK"},
#         {"name": "Muñoz", "rating": 82, "pos": "DEF"}, {"name": "Clyne", "rating": 70, "pos": "DEF"},
#         {"name": "Richards", "rating": 79, "pos": "DEF"}, {"name": "Lacroix", "rating": 81, "pos": "DEF"},
#         {"name": "Riad", "rating": 72, "pos": "DEF"}, {"name": "Canvot", "rating": 73, "pos": "DEF"},
#         {"name": "Mitchell", "rating": 79, "pos": "DEF"}, {"name": "Sosa", "rating": 72, "pos": "DEF"},
#         {"name": "Wharton", "rating": 81, "pos": "MID"}, {"name": "Kamada", "rating": 78, "pos": "MID"},{"name": "Doucouré", "rating": 77, "pos": "MID"},
#         {"name": "Hughes", "rating": 77, "pos": "MID"}, {"name": "Devenny", "rating": 71, "pos": "MID"}, {"name": "Lerma", "rating": 77, "pos": "MID"},
#         {"name": "Sarr", "rating": 80, "pos": "FWD"}, {"name": "Johnson", "rating": 79, "pos": "FWD"},
#         {"name": "Yeremy Pino", "rating": 79, "pos": "FWD"}, {"name": "Larsen", "rating": 77, "pos": "FWD"}, {"name": "Guessand", "rating": 78, "pos": "FWD"},
#         {"name": "Mateta", "rating": 82, "pos": "FWD"}, {"name": "Nketiah", "rating": 75, "pos": "FWD"},
#         {"name": "Uche", "rating": 76, "pos": "FWD"}
#     ]},

#         "Leeds": {"emoji": "🟡⚪", "players": [
#         {"name": "Darlow", "rating": 74, "pos": "GK"}, {"name": "Lucas Perri", "rating": 78, "pos": "GK"}, {"name": "Meslier", "rating": 71, "pos": "GK"},
#         {"name": "Bogle", "rating": 76, "pos": "DEF"}, {"name": "Justin", "rating": 75, "pos": "DEF"},
#         {"name": "Rodon", "rating": 77, "pos": "DEF"}, {"name": "Bijol", "rating": 77, "pos": "DEF"},
#         {"name": "Bornauw", "rating": 74, "pos": "DEF"}, {"name": "Struijk", "rating": 76, "pos": "DEF"}, 
#         {"name": "Gudmundsson", "rating": 77, "pos": "DEF"}, {"name": "Byram", "rating": 72, "pos": "DEF"},
#         {"name": "Ampadu", "rating": 78, "pos": "MID"}, {"name": "Tanaka", "rating": 76, "pos": "MID"}, {"name": "Gruev", "rating": 75, "pos": "MID"},
#         {"name": "Aaronson", "rating": 76, "pos": "MID"}, {"name": "Longstaff", "rating": 76, "pos": "MID"},
#         {"name": "Stach", "rating": 79, "pos": "MID"}, {"name": "Buonanotte", "rating": 75, "pos": "MID"},
#         {"name": "Okafor", "rating": 76, "pos": "FWD"}, {"name": "Gnonto", "rating": 74, "pos": "FWD"}, {"name": "Nmecha", "rating": 76, "pos": "FWD"},
#         {"name": "Calvert-Lewin", "rating": 77, "pos": "FWD"}, {"name": "James", "rating": 76, "pos": "MID"}, {"name": "Piroe", "rating": 75, "pos": "MID"}
#     ]},

#         "West Ham": {"emoji": "⚒️", "players": [
#         {"name": "Areola", "rating": 77, "pos": "GK"}, {"name": "Hermansen", "rating": 75, "pos": "GK"}, {"name": "Fabiański", "rating": 74, "pos": "GK"},
#         {"name": "Wan-Bissaka", "rating": 79, "pos": "DEF"}, {"name": "Walker-Peters", "rating": 76, "pos": "DEF"},
#         {"name": "Mavropanos", "rating": 76, "pos": "DEF"}, {"name": "Disasi", "rating": 77, "pos": "DEF"},
#         {"name": "Todibo", "rating": 78, "pos": "DEF"}, {"name": "Kilman", "rating": 76, "pos": "DEF"},
#         {"name": "Scarles", "rating": 72, "pos": "DEF"}, {"name": "Diouf", "rating": 77, "pos": "DEF"},
#         {"name": "Souček", "rating": 76, "pos": "MID"}, {"name": "Potts", "rating": 73, "pos": "MID"},
#         {"name": "Magassa", "rating": 73, "pos": "MID"}, {"name": "Kanté", "rating": 62, "pos": "MID"},
#         {"name": "Orford", "rating": 61, "pos": "MID"}, {"name": "Mateus Fernandes", "rating": 78, "pos": "MID"},
#         {"name": "Bowen", "rating": 83, "pos": "FWD"}, {"name": "Adama Traoré", "rating": 76, "pos": "FWD"},
#         {"name": "Summerville", "rating": 77, "pos": "FWD"}, {"name": "Lamadrid", "rating": 70, "pos": "FWD"},
#         {"name": "Castellanos", "rating": 80, "pos": "FWD"}, {"name": "Wilson", "rating": 77, "pos": "FWD"},
#         {"name": "Pablo Felipe", "rating": 73, "pos": "FWD"}
#     ]},

#         "Burnley": {"emoji": "🍷", "players": [
#         {"name": "Dúbravka", "rating": 78, "pos": "GK"}, {"name": "Weiß", "rating": 69, "pos": "GK"},
#         {"name": "Walker-Peters", "rating": 77, "pos": "DEF"}, {"name": "Roberts", "rating": 74, "pos": "DEF"},
#         {"name": "Humphreys", "rating": 74, "pos": "DEF"}, {"name": "Worrall", "rating": 73, "pos": "DEF"},
#         {"name": "Tuanzebe", "rating": 73, "pos": "DEF"}, {"name": "Estève", "rating": 76, "pos": "DEF"}, {"name": "Ekdal", "rating": 72, "pos": "DEF"},
#         {"name": "Lucas Pires", "rating": 74, "pos": "DEF"}, {"name": "Hartman", "rating": 76, "pos": "DEF"}, {"name": "Beyer", "rating": 73, "pos": "DEF"},
#         {"name": "Ugochukwu", "rating": 76, "pos": "MID"}, {"name": "Florentino", "rating": 78, "pos": "MID"},{"name": "Laurent", "rating": 73, "pos": "MID"},
#         {"name": "Hannibal", "rating": 74, "pos": "MID"}, {"name": "Ward-Prowse", "rating": 75, "pos": "MID"}, {"name": "Cullen", "rating": 77, "pos": "MID"},
#         {"name": "Edwards", "rating": 75, "pos": "MID"},
#         {"name": "Agyei", "rating": 63, "pos": "MID"}, {"name": "Anthony", "rating": 76, "pos": "FWD"},
#         {"name": "Bruun Larsen", "rating": 73, "pos": "FWD"}, {"name": "Flemming", "rating": 75, "pos": "FWD"},
#         {"name": "Tchaouna", "rating": 72, "pos": "FWD"}, {"name": "Broja", "rating": 72, "pos": "FWD"},
#         {"name": "Foster", "rating": 73, "pos": "FWD"}, {"name": "Barnes", "rating": 70, "pos": "FWD"},
#         {"name": "Amdouni", "rating": 75, "pos": "FWD"}, {"name": "Trésor", "rating": 73, "pos": "FWD"},
#     ]},

#         "Wolves": {"emoji": "🐺", "players": [
#         {"name": "José Sá", "rating": 76, "pos": "GK"}, {"name": "Johnstone", "rating": 76, "pos": "GK"},
#         {"name": "Tchatchoua", "rating": 74, "pos": "DEF"}, {"name": "Pedro Lima", "rating": 68, "pos": "DEF"},
#         {"name": "Bueno", "rating": 76, "pos": "DEF"}, {"name": "Toti", "rating": 75, "pos": "DEF"},
#         {"name": "Doherty", "rating": 74, "pos": "DEF"}, {"name": "Mosquera", "rating": 72, "pos": "DEF"},
#         {"name": "Krejčí", "rating": 78, "pos": "DEF"}, {"name": "Hugo Bueno", "rating": 75, "pos": "DEF"},
#         {"name": "Wolfe", "rating": 73, "pos": "DEF"}, {"name": "André", "rating": 78, "pos": "MID"},
#         {"name": "Gomes", "rating": 76, "pos": "MID"}, {"name": "João Gomes", "rating": 78, "pos": "MID"},
#         {"name": "Bellegarde", "rating": 75, "pos": "MID"}, {"name": "Mateus Martins", "rating": 70, "pos": "MID"},
#         {"name": "Armstrong", "rating": 73, "pos": "FWD"}, {"name": "Rodrigo Gomes", "rating": 73, "pos": "FWD"},
#         {"name": "Arokodare", "rating": 76, "pos": "FWD"}, {"name": "Hwang Hee-chan", "rating": 74, "pos": "FWD"}
#     ]}
